### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kaizau** [kaizau/try-webxr#1]
### Pre-Announce
- [x] Order Google Cardboards
- [x] Book time + venue
- [x] Create Meetup event
- [x] Reach out to relevant groups, lists

### Pre-Event
- [x] Order Google Cardboards
- [x] Create slideshow / cheatsheet
- [x] Create getting started instructions / template
- [x] Create toy demo(s)

**Comment by kaizau** [comment]
💥
